# deployment of main application
apiVersion: apps/v1
kind: Deployment
metadata:
  name: meli-proxy-deployment
spec:
  selector:
    matchLabels:
      app: meli-proxy
  replicas: 1
  template:
    metadata:
      labels:
        app: meli-proxy
    spec:
      containers:
      - name: meli-proxy
        image: lockhaven72/meli-proxy:latest
        resources:
          requests:
            memory: "100Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "1"
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 3
        env:
        - name: DB_HOST
          value: meli-proxy-db-service.default
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: mercadolibre
        - name: DB_PASSWORD
          value: proxy
        - name: MAX_USER_REQUESTS
          value: "5"
        - name: MAX_ENDPOINT_REQUESTS
          value: "5"
        - name: MAX_USER_ENDPOINT_REQUESTS
          value: "5"
        - name: DJANGO_SECRET_KEY
          value: ")bolt%5q&bosg=xi^n^$$(-vey-m38^2m5f1ay%n5)b0ezi^0tv"
        - name: MERCADOLIBRE_API
          value: https://api.mercadolibre.com
        volumeMounts:
        - name:  db-migration
          mountPath:  ./migrations
      volumes:
      - name:  db-migration
        persistentVolumeClaim:
          claimName: meli-proxy-pvc