# deployment of main application
apiVersion: apps/v1
kind: Deployment
metadata:
  name: meli-proxy-deployment
spec:
  selector:
    matchLabels:
      app: meli-proxy
  replicas: 1
  template:
    metadata:
      labels:
        app: meli-proxy
    spec:
      containers:
      - name: meli-proxy
        image: lockhaven72/meli-proxy:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "128m"
        ports:
        - containerPort: 8080
        env:
        - name: DB_HOST
          value: meli-proxy-db-service.default
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: mercadolibre
        - name: DB_PASSWORD
          value: proxy
        - name: MAX_USER_REQUESTS
          value: "5"
        - name: MAX_ENDPOINT_REQUESTS
          value: "5"
        - name: MAX_USER_ENDPOINT_REQUESTS
          value: "5"
        - name: DJANGO_SECRET_KEY
          value: ")bolt%5q&bosg=xi^n^$$(-vey-m38^2m5f1ay%n5)b0ezi^0tv"
        - name: MERCADOLIBRE_API
          value: https://api.mercadolibre.com