apiVersion: v1
kind: Service
metadata:
  name: meli-proxy-metrics-service
spec:
  selector:
    app: meli-proxy-metrics
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 9090