apiVersion: v1
kind: ConfigMap
metadata:
  name: meli-proxy-metrics-configmap
data:
  prometheus.yml : |-
    # Prometheus configuration file
    global:
        scrape_interval:     5s # Set the scrape interval to every 5 seconds. Default is every 1 minute.
        evaluation_interval: 5s # Evaluate rules every 5 seconds. The default is every 1 minute.
        # scrape_timeout is set to the global default (10s).
      
    # Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
    rule_files:
    # - "alert_rules.yml"
    # - "first_rules.yml"
    # - "second_rules.yml"
      
    # A scrape configuration containing exactly one endpoint to scrape:
    # Here it's Prometheus itself.
    scrape_configs:
    # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
        - job_name: 'prometheus'
        # metrics_path defaults to '/metrics'
        # scheme defaults to 'http'.
          static_configs:
          - targets: ['localhost:9090']

        - job_name: 'meli_proxy'
          metrics_path: '/metrics'
          scrape_interval: 5s
          static_configs:
          - targets: ['meli-proxy-service.default:8080']
            labels:
              alias: "meli_proxy"