apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: meli-proxy-monitoring-ingress
  labels:
      name: meli-proxy-monitoring
spec:
  rules:
  - host: localhost
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: meli-proxy-monitoring-service
            port:
              number: 3000
